describe('template spec', () => {
  beforeEach(()=>{
    cy.visit('/')
    cy.wait(1000)
  })
  it('header content test passed', () => {
    cy.get('h1').should('contain.text',"Todo web")
  })
  it('add and delete todo passed',()=>{
    cy.get('textarea').should('have.text',"")
    cy.get('textarea').type("task 1")
    cy.getElement('add-todo-button').click()
    cy.get('h2').should('contain.text',"Incomplete")
    cy.getElement('single-todo').should('contain.text',"task 1")
    cy.getElement('single-todo').its(0).within(()=>{
      cy.getElement('delete-button').click()
    })
    cy.getElement('single-todo').should('not.exist')
  })
  it('filter test passed',()=>{
    cy.get('select').should('not.be.empty')
    cy.get('textarea').type("task 1")
    cy.getElement('add-todo-button').click()
    cy.get('h2').should('contain.text',"Incomplete")
    cy.getElement('change-state-button-done').click()
    cy.get('h2').should('contain.text',"Complete")
    cy.get('textarea').clear()
    cy.get('textarea').type("task 2")
    cy.getElement('add-todo-button').click()
    cy.get('textarea').clear()
    cy.get('h2').should('contain.text',"Incomplete")
    cy.get('h2').should('contain.text',"Complete")
    cy.get('select').select('complete')
    cy.getElement('incomplete-header').should('not.exist')
    cy.getElement('complete-header').should('exist')
    cy.get('select').select('incomplete')
    cy.getElement('complete-header').should('not.exist')
    cy.getElement('incomplete-header').should('exist')
    cy.get('select').select('all')
    cy.getElement('complete-header').should('exist')
    cy.getElement('incomplete-header').should('exist')
  })
  it("update test passed",()=>{
    cy.get('textarea').type("task 1")
    cy.getElement('add-todo-button').click()
    cy.getElement('single-todo').should('contain.text',"task 1")
    cy.getElement('update-button').should('contain.text','update')
    cy.getElement('update-button').click()
    cy.getElement('update-button').should('contain.text','undo')
    cy.getElement('update-input').should('exist')
    cy.getElement('update-input').type(' updated')
    cy.getElement('update-form').submit()
    cy.getElement('single-todo').should('contain.text',"task 1 updated")
  })
})